import 'package:flutter/material.dart';
import 'package:hive/hive.dart';
import 'package:ionicons/ionicons.dart';
import 'package:trackroutine/constants/colors.dart';
import 'package:trackroutine/utils/color_Utilities.dart';

class IconSelectableView extends StatefulWidget {
  @override
  _IconSelectableViewState createState() => _IconSelectableViewState();
}

class _IconSelectableViewState extends State<IconSelectableView> {
  IconData? selectedIcon;

  // List of Ionicons icons to display
  final List<IconData> iconList = [
    Ionicons.home,
    Ionicons.settings,
    Ionicons.add_circle,
    Ionicons.search,
    Ionicons.person,
    Ionicons.heart,
    Ionicons.cart,
    Ionicons.calendar,
    Ionicons.notifications,
    Ionicons.mail,
    Ionicons.location,
    Ionicons.volume_high,
    Ionicons.airplane,
    Ionicons.game_controller,
    Ionicons.cloud,
    Ionicons.cloud_upload,
    Ionicons.cloud_download,
    Ionicons.bicycle,
    Ionicons.camera,
    Ionicons.moon,
    Ionicons.sunny,
    Ionicons.star,
    Ionicons.flash,
    Ionicons.flashlight,
    Ionicons.pencil,
    Ionicons.print,
    Ionicons.bus,
    Ionicons.document,
    Ionicons.phone_portrait,
    Ionicons.phone_landscape,
    Ionicons.barbell,
    Ionicons.refresh,
    Ionicons.search_circle,
    Ionicons.text,
    Ionicons.shuffle,
    Ionicons.wifi,
    Ionicons.game_controller,
    Ionicons.volume_mute,
    Ionicons.mic,
    Ionicons.musical_note,
    Ionicons.grid,
    Ionicons.list,
    Ionicons.toggle,
    Ionicons.bluetooth,
    Ionicons.battery_charging,
    Ionicons.car,
    Ionicons.flag,
    Ionicons.lock_closed,
    Ionicons.lock_open,
    Ionicons.rainy,
    Ionicons.sunny,
    Ionicons.wine,
    Ionicons.git_merge,
    Ionicons.git_network,
    Ionicons.git_pull_request,
    Ionicons.git_branch,
    Ionicons.git_commit,
    Ionicons.git_compare,
    Ionicons.git_compare_sharp,
    Ionicons.git_commit,
    Ionicons.home_outline,
    Ionicons.apps,
    Ionicons.airplane_outline,
    Ionicons.car_outline,
    Ionicons.cloud_outline,
    Ionicons.camera_outline,
    Ionicons.moon_outline,
    Ionicons.sunny_outline,
    Ionicons.search_outline,
    Ionicons.wine_outline,
    Ionicons.flag_outline,
    Ionicons.lock_closed_outline,
    Ionicons.lock_open_outline,
    Ionicons.rainy_outline,
    Ionicons.rainy_sharp,
    Ionicons.water,
    Ionicons.cart_outline,
    Ionicons.cart_sharp,
    Ionicons.checkmark,
    Ionicons.checkmark_outline,
    Ionicons.close,
    Ionicons.close_outline,
    Ionicons.cloudy,
    Ionicons.cloudy_night,
    Ionicons.funnel,
    Ionicons.cafe,
    Ionicons.cog,
    Ionicons.bar_chart,
    Ionicons.book,
    Ionicons.call,
    Ionicons.call_outline,
    Ionicons.chatbubbles,
    Ionicons.chatbubbles_outline,
    Ionicons.chatbox,
    Ionicons.chatbox_outline,
    Ionicons.contract,
    Ionicons.copy,
    Ionicons.cube,
    Ionicons.desktop,
    Ionicons.download,
    Ionicons.download_outline,
    Ionicons.diamond,
    Ionicons.document_outline,
    Ionicons.exit,
    Ionicons.exit_outline,
    Ionicons.heart,
    Ionicons.heart_circle,
    Ionicons.flashlight_outline,
    Ionicons.gift,
    Ionicons.gift_outline,
    Ionicons.headset,
    Ionicons.headset_outline,
    Ionicons.help,
    Ionicons.help_outline,
    Ionicons.happy,
    Ionicons.happy_outline,
    Ionicons.hourglass,
    Ionicons.hourglass_outline,
    Ionicons.image,
    Ionicons.image_outline,
    Ionicons.infinite,
    Ionicons.information,
    Ionicons.information_circle_outline,
    Ionicons.pie_chart,
    Ionicons.pie_chart_outline,
    Ionicons.podium,
    Ionicons.podium_outline,
    Ionicons.refresh_circle,
    Ionicons.reorder_two,
    Ionicons.reorder_three,
    Ionicons.repeat,
    Ionicons.aperture,
    Ionicons.refresh_circle,
    Ionicons.search_sharp,
    Ionicons.server,
    Ionicons.shield,
    Ionicons.shield_outline,
    Ionicons.star_outline,
    Ionicons.star_half,
    Ionicons.shapes,
    Ionicons.star_sharp,
    Ionicons.stop,
    Ionicons.stop_outline,
    Ionicons.trophy,
    Ionicons.trophy_outline,
    Ionicons.trending_down,
    Ionicons.trending_up,
    Ionicons.trash,
    Ionicons.trash_outline,
    Ionicons.time,
    Ionicons.time_outline,
    Ionicons.videocam,
    Ionicons.videocam_outline,
    Ionicons.volume_mute_outline,
    Ionicons.warning,
    Ionicons.warning_outline,
    Ionicons.wifi_outline,
    Ionicons.wine_outline,
    Ionicons.aperture_outline,
    Ionicons.aperture_sharp,
    Ionicons.airplane,
    Ionicons.airplane_outline,
    Ionicons.airplane_sharp,
    Ionicons.alert,
    Ionicons.alert_circle,
    Ionicons.arrow_back,
    Ionicons.arrow_forward,
    Ionicons.arrow_down,
    Ionicons.arrow_up,
    Ionicons.at,
    Ionicons.barcode,
    Ionicons.battery_full,
    Ionicons.battery_half,
    Ionicons.battery_dead,
    Ionicons.beaker,
    Ionicons.bookmark,
    Ionicons.bookmark_outline,
    Ionicons.briefcase,
    Ionicons.bulb,
    Ionicons.camera,
    Ionicons.camera_reverse_outline,
    Ionicons.caret_back,
    Ionicons.caret_forward,
    Ionicons.cart_outline,
    Ionicons.cloud_circle,
    Ionicons.cloud_download_outline,
    Ionicons.cloud,
    Ionicons.cloud_upload_outline,
    Ionicons.cloud_upload_sharp,
    Ionicons.color_fill,
    Ionicons.color_palette,
    Ionicons.contrast,
    Ionicons.desktop_outline,
    Ionicons.phone_landscape,
    Ionicons.tablet_landscape,
    Ionicons.call_sharp,
    Ionicons.egg,
    Ionicons.mail,
    Ionicons.mail_open,
    Ionicons.eye,
    Ionicons.eye_off,
    Ionicons.fast_food,
    Ionicons.file_tray,
    Ionicons.file_tray_full,
    Ionicons.flash_off,
    Ionicons.flask,
    Ionicons.color_fill,
    Ionicons.gift_sharp,
    Ionicons.aperture,
    Ionicons.hammer,
    Ionicons.at,
    Ionicons.hardware_chip,
    Ionicons.help_circle,
    Ionicons.home_sharp,
    Ionicons.laptop,
    Ionicons.bulb,
    Ionicons.link,
    Ionicons.lock_closed_sharp,
    Ionicons.lock_open_sharp,
    Ionicons.mail_open,
    Ionicons.map,
    Ionicons.medal,
    Ionicons.megaphone,
    Ionicons.moon_sharp,
    Ionicons.musical_note,
    Ionicons.notifications,
    Ionicons.podium_sharp,
    Ionicons.print_sharp,
    Ionicons.pulse,
    Ionicons.radio,
    Ionicons.receipt_sharp,
    Ionicons.refresh_sharp,
    Ionicons.recording,
    Ionicons.radio_button_on,
    Ionicons.school,
    Ionicons.search_sharp,
    Ionicons.share,
    Ionicons.radio_button_off,
    Ionicons.skull,
    Ionicons.snow,
    Ionicons.sunny_sharp,
    Ionicons.swap_vertical,
    Ionicons.swap_horizontal,
    Ionicons.tablet_landscape,
    Ionicons.tablet_portrait,
    Ionicons.laptop,
    Ionicons.tablet_portrait,
    Ionicons.text_outline,
    Ionicons.timer,
    Ionicons.trending_up_sharp,
    Ionicons.tv,
    Ionicons.wallet,
    Ionicons.wine_sharp,
  ];

  void onIconTap(IconData icon) {
    setState(() {
      selectedIcon = icon;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      backgroundColor: kSeconderyColors,
      body: Padding(
        padding: const EdgeInsets.all(8.0),
        child: Column(
          mainAxisAlignment: MainAxisAlignment.start,
          crossAxisAlignment: CrossAxisAlignment.center,
          children: [
            if (selectedIcon != null)
              Container(
                decoration: BoxDecoration(
                  color: kDeepCharcoalGray,
                  borderRadius: BorderRadius.circular(15),
                ),
                child: Icon(
                  selectedIcon,
                  size: 25,
                  color: HexColor("FFD700"),
                ),
              ),
            SizedBox(height: 20),
            Text(
              selectedIcon != null ? "Selected Icon" : "No Icon Selected",
              style: TextStyle(fontSize: 16, color: Colors.grey),
            ),
            SizedBox(height: 20),
            Expanded(
              child: GridView.builder(
                gridDelegate: SliverGridDelegateWithFixedCrossAxisCount(
                  crossAxisCount: 5, // Number of icons per row
                  crossAxisSpacing: 8.0,
                  mainAxisSpacing: 8.0,
                ),
                itemCount: iconList.length,
                itemBuilder: (context, index) {
                  return Container(
                    decoration: BoxDecoration(
                      color: kSeconderyColors,
                      borderRadius: BorderRadius.circular(15),
                    ),
                    child: IconButton(
                      icon: Icon(iconList[index]),
                      onPressed: () => onIconTap(iconList[index]),
                      iconSize: 25,
                      color: Colors.black,
                    ),
                  );
                },
              ),
            ),
          ],
        ),
      ),
    );
  }
}

// void main() {
//   runApp(MaterialApp(
//     home: IconSelectableView(),
//   ));
// }
